apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariantSet
metadata: # kpt-merge: /cachingdns-edge
  name: cachingdns-edge
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|PackageVariantSet|default|cachingdns-edge'
spec:
  upstream:
    package:
      repo: nephio-testorg-packages
      name: cachingdns-edge
    revision: v2
  targets:
  - repositories:
      nephio.org/site-type: edge
